branches:
  only:
    - master

language: perl6

perl6:
  - latest

install:
  - rakudobrew build zef
#  - zef --debug --/test install Crane
#  - zef --debug --/test install Config::TOML
  - zef --/test --depsonly install .

#cache:
#  directories:
#    - $TRAVIS_BUILD_DIR/.rakudobrew
