#!/home/marcel/bin/fcopy
#-------------------------------------------------------------------------------
# What to expect
# > fcopy config fotos opt1
#   get options and filters 
#   then merge from options.fotos and filters.fotos
#   then merge from options.fotos.opt1, etc.
#
#-------------------------------------------------------------------------------
[filters]
  filter-sequence       = [ 'i=include', 'e=exclude', 'f=filter', 'e=ex2']
  exclude               = [ 'old', 'Old', '*~']
  ex2                   = [ '*.html']
  include               = [ '*.pdf' ]
  filter                = [ '- Test/', '- test' ]

[options]
  dry-run               = true
  verbose               = 2
  times                 = true
  log                   = true

[targets]
  sources                = [ '/home/Data/Fotos/' ]
  source                = '/home/Data/Fotos/'
  destination           = '/mnt/Backup/Fotos'

#-------------------------------------------------------------------------------
[targets.fotos]
#  sources                = [ '/home/Data/Fotos/' ]
  source                = '/home/Data/Fotos/'
  destination           = '/mnt/Backup/Fotos'

[options.fotos]
  log                   = false
  dry-run               = false

[targets.fotos.remote]
  destination           = 'marcel@192.168.192.253:/home/Data/Fotos/'

[filters.fotos]
  exclude               = [ '.precomp']
  filter                = [ ]

