#!/home/marcel/bin/fcopy
#-------------------------------------------------------------------------------
# What to expect
# > fcopy config fotos opt1
#   get options and filters
#   then merge from options.src and filters.src
#   then merge from options.src.opt1, etc.
#
#-------------------------------------------------------------------------------
[filters]
  filter-sequence       = [ 'i=include', 'e=exclude', 'f=filter', 'e=ex2']
  exclude               = [ 'old', 'Old', '*~']
  ex2                   = [ '*.html']
  include               = [ '*.pdf' ]
  filter                = [ '- Test/', '- test' ]

[options]
  dry-run               = true
  verbose               = 2
  times                 = true
  log                   = true

#[targets]
#  sources                = [ '/home/Data/Fotos/' ]
#  source                = '/home/Data/Fotos/'
#  destination           = '/mnt/Backup/Fotos'

#-------------------------------------------------------------------------------
[targets.src]
  source                = 't/src-dir'

[options.src]
  log                   = false
  dry-run               = false

[filters.src]
  exclude               = [ '.precomp']
  filter                = [ ]

[options.src.remote]
  log                   = true

[targets.src.remote]
  destination           = 'marcel@192.168.192.253:/tmp/dest-dir'

[options.src.dup]
  dry-run               = true

[targets.src.dup]
#  sources               = [ '/home/Foo/Fotos/', '/home/Bar/Fotos/' ]
  destination           = 't/dest-dir'
